name: cleanarchtdd
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  dartz: 0.10.1
  dio: 5.1.2
  equatable: 2.0.5
  flutter_launcher_icons: 0.13.1
  flutter_native_splash: 2.3.5
  font_awesome_flutter: 10.4.0
  internet_connection_checker: 1.0.0+1
  intl: 0.18.1
  package_info: 2.0.2
  path: 1.8.3
  provider: 6.0.5
  rxdart: 0.27.7
  shared_preferences: 2.2.1
  shimmer: 3.0.0
  top_snackbar_flutter: 3.1.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/self-azul-icon.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/self-azul-icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/self-azul-icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: 1.24.3

flutter:

  uses-material-design: true

  assets:
    - assets/placeholder.png
    - assets/img-not-found.png
    - assets/self-azul-sem-fundo.png
    - assets/clock-store-icon.png
    - assets/self-brancal-sem-fundo.png 

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  
